name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
         python-version: "3.9"

      - name: Install dependencies and bundle code
        env:
          CI: true
        run: |
          npm ci
          zip -r publish.zip ./*
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name rx_test_2 --zip-file fileb://publish.zip --region ap-south-1
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.BETA_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BETA_AWS_SECRET_ACCESS_KEY }}
